## Buscar students
GET http://localhost:3000/students/
Accept: application/json

## Buscar students por série
### Buscar alunos por série
GET http://localhost:3000/students/PW I
Accept: application/json

## Create student
### Criar novo aluno
POST https://api-students-production.up.railway.app/students
Content-Type: application/json

{
  "name": "Alessandro Barbosa Vitorio",
  "login": "alevitorio",
  "email": "alessandro@gmail.com",
  "avatar": "https://avatars.githubusercontent.com/u/43097497?v=4"
}

